apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd # default
  # finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: "5.25.0"
    helm:
      values: |
        ## Argo CD configuration
        ## Ref: https://github.com/argoproj/argo-cd
        ##
        ## openshift:
          # -- enables using arbitrary uid for argo repo server
          # enabled: false
        
        ## Argo Configs
        configs:
          # General Argo CD configuration
          ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
          cm:
            kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"
            # Ugh! Really? https://codefresh.io/blog/argo-cd-application-dependencies/
            # https://github.com/argoproj/argo-cd/issues/7437
            resource.customizations.health.argoproj.io_Application: |
              hs = {}
              hs.status = "Progressing"
              hs.message = ""
              if obj.status ~= nil then
                if obj.status.health ~= nil then
                  hs.status = obj.status.health.status
                  if obj.status.health.message ~= nil then
                    hs.message = obj.status.health.message
                  end
                end
              end
              return hs
        
        #configs:
          # Argo CD sensitive data
          # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#sensitive-data-and-sso-client-secrets
          # secret:
            # -- Bcrypt hashed admin password
            ## Argo expects the password in the secret to be bcrypt hashed. You can create this hash with
            ## `htpasswd -nbBC 10 "" $ARGO_PWD | tr -d ':\n' | sed 's/$2y/$2a/'`
            # argocdServerAdminPassword: ""
            # -- Admin password modification time. Eg. `"2006-01-02T15:04:05Z"`
            # @default -- `""` (defaults to current time)
            # argocdServerAdminPasswordMtime: ""
        repoServer:
          env:
            - name: XDG_CONFIG_HOME
              value: /.config
            - name: SOPS_AGE_KEY_FILE
              value: /.config/sops/age/keys.txt
            - name: GNUPGHOME
              value: /gnupg-home/.gnupg
            #- name: HTTPS_PROXY
            #  value: "192.168.1.121"
            #- name: HTTP_PROXY
            #  value:
            #- name: NO_PROXY
            #  value:
          initContainers:
            - name: install-ksops
              image: viaductoss/ksops:v4.0.1
              command: ["/bin/sh", "-c"]
              args:
                - echo "Installing KSOPS...";
                  mv ksops /custom-tools/;
                  mv $GOPATH/bin/kustomize /custom-tools/;
                  echo "Done.";
              volumeMounts:
                - mountPath: /custom-tools
                  name: custom-tools
            - name: import-gpg-key
              image: argoproj/argocd:v2.6.4
              command: ["gpg", "--import","/sops-gpg/sops.asc"]
              env:
                - name: GNUPGHOME
                  value: /gnupg-home/.gnupg
              volumeMounts:
                - mountPath: /sops-gpg
                  name: sops-gpg
                - mountPath: /gnupg-home
                  name: gnupg-home
          volumes:
            - name: custom-tools
              emptyDir: {}  
            - name: sops-age
              secret:
                secretName: sops-age
            - name: gnupg-home
              emptyDir: {}
            - name: sops-gpg
              secret:
                secretName: sops-gpg
            #- name: ca-certs
            #  configMap:
            #    name: ca-certs
          volumeMounts:
            - mountPath: /usr/local/bin/kustomize
              name: custom-tools
              subPath: kustomize
            - mountPath: /usr/local/bin/ksops
              name: custom-tools
              subPath: ksops
            - mountPath: /.config/sops/age/keys.txt
              name: sops-age
              subPath: keys.txt
            - mountPath: /gnupg-home/.gnupg
              name: gnupg-home
              subPath: .gnupg
            #- mountPath: /etc/ssl/certs/ca-certificates.crt
            #  name: ca-certs
            #  subPath: ca-certificates.crt
        server:
          #configEnabled: true
          #config:
          #  repositories: |
          #    - name: argo-helm
          #      type: helm
          #      url: https://argoproj.github.io/argo-helm
          #additionalApplications: 
          #  - name: argocd
          #    namespace: argocd
          #    destination:
          #      namespace: argocd
          #      server: https://kubernetes.default.svc
          #    project: argocd
          #    source:
          #      helm:
          #        version: v3
          #        valueFiles:
          #        - values.yaml
          #        - ../values-override.yaml
          #      path: argocd-install/argo-cd
          #      repoURL: https://github.com/kurtburak/argocd.git
          #      targetRevision: HEAD
          #    syncPolicy:
          #      syncOptions:
          #      - CreateNamespace=true
          #  - name: argocd-apps
          #    namespace: argocd
          #    destination:
          #      namespace: argocd
          #      server: https://kubernetes.default.svc
          #    project: argocd
          #    source:
          #      path: argocd-apps
          #      repoURL: https://github.com/kurtburak/argocd.git
          #      targetRevision: HEAD
          #      directory:
          #        recurse: true
          #        jsonnet: {}
          #    syncPolicy:
          #      automated:
          #        selfHeal: true
          #        prune: true
          #  - name: argocd-appprojects
          #    namespace: argocd
          #    destination:
          #      namespace: argocd
          #      server: https://kubernetes.default.svc
          #    project: argocd
          #    source:
          #      path: argocd-appprojects
          #      repoURL: https://github.com/kurtburak/argocd.git
          #      targetRevision: HEAD
          #      directory:
          #        recurse: true
          #        jsonnet: {}
          #    syncPolicy:
          #      automated:
          #        selfHeal: true
          #        prune: true
          #additionalProjects: 
          #- name: argocd
          #  namespace: argocd
          #  additionalLabels: {}
          #  additionalAnnotations: {}
          #  description: Argocd Project
          #  sourceRepos:
          #  - '*'
          #  destinations:
          #  - namespace: argocd
          #    server: https://kubernetes.default.svc
          #  clusterResourceWhitelist:
          #  - group: '*'
          #    kind: '*'
          #  orphanedResources:
          #    warn: false
        #  extraArgs:
        #    - --insecure
        #  configManagementPlugins: |
          service:
            type: LoadBalancer


      # - ../../argocd/values.yaml # TODO: move me here
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
