apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ksops
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ksops
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated: {}
  source:
    path: infrastructure/ksops
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
