apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret-sync
  namespace: argocd
spec:
  data:
    - remoteRef:
        key: ArgoCD
        property: SecretKey
      secretKey: SecretKey
    - remoteRef:
        key: ArgoCD
        property: OpenIDClientID
      secretKey: OpenIDClientID
    - remoteRef:
        key: ArgoCD
        property: OpenIDClientSecret
      secretKey: OpenIDClientSecret
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    name: argocd-secret
    template:
      engineVersion: v2
      data:
        server.secretkey: '{{`{{ .SecretKey }}`}}'
        oidc.clientID: '{{`{{ .OpenIDClientID }}`}}'
        oidc.clientSecret: '{{`{{ .OpenIDClientSecret }}`}}'
